config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'products#index'
  devise_for :users, controllers: {
      registrations: 'users/registrations'
  }

  resources :stores, only: [] do
    get '/connect', on: :collection, to: 'stores#connect'
  end

  resources :products, only: [:index, :show] do
    member do
      get '/orders', to: 'products#orders'
      get '/orders_unplaced', to: 'products#orders_unplaced'
      get '/customers', to: 'products#customers'
      get '/sales', to: 'products#sales'
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, presence: true, uniqueness: true
  validates :password_confirmation, presence: true, if: Proc.new { |u| u.password.present? }
  validates_presence_of :api_url, :access_token

  def shop_host
    api_uri.host
  end

  def shop_name
    api_uri.path.gsub('/rs/shops/', '')
  end

  def api_uri
    URI(api_url)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery prepend: true
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def index
    page = params[:page] || 1
    @products = shop.products(sort: :name, page: page)
  end

  def show
    @product = shop.product(params[:id])
  end

  def orders
    @orders = Orders::Listing.new(shop).by_product(params[:id])
    @title_prefix = 'Placed'

    render partial: 'products/partials/orders', layout: false
  end

  def orders_unplaced
    @orders = Orders::Listing.new(shop).by_product(params[:id], false)
    @title_prefix = 'Unplaced'

    render partial: 'products/partials/orders', layout: false
  end

  def customers
    @customers = Customers::Listing.new(shop).by_product(params[:id])
    @product = shop.product(params[:id])

    render partial: 'products/partials/customers', layout: false
  end

  def sales
    @sales = shop.sales(product_id: params[:id])

    render partial: 'products/partials/sales', layout: false
  end

  private
    def shop
      @shop ||= Epages::REST::Shop.new(
        current_user.shop_host,
          current_user.shop_name,
          current_user.access_token
      )
    end
end

app/controllers/stores_controller.rb
# frozen_string_literal: true

class StoresController < ApplicationController
  skip_before_action :authenticate_user!, only: :connect

  def connect
    session.merge!(account_params)

    redirect_to new_user_registration_path
  end

  private

    def account_params
      params.permit(:code, :api_url, :return_url, :access_token_url, :signature)
    end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # POST /resource
  def create
    unless session.has_key?(:code) &&
        session.has_key?(:access_token_url) &&
        session.has_key?(:api_url)
      handle_error t('errors.messages.no_oauth_data')
      return
    end

    unless Auth::SignatureVerify.new(
      session[:code],
      session[:access_token_url],
      session[:signature]
    ).call
      handle_error t('errors.messages.invalid_signature')
      return
    end

    begin
      access_token = Adapter::EPages.create_access_token(session[:code], session[:access_token_url])

      super do |user|
        user.access_token = access_token
        user.api_url = session[:api_url]
        user.save!
      end
    rescue ArgumentError => exception
      handle_error exception.message
      return
    end
  end

  private
    def handle_error(message)
      flash.alert = message
      redirect_to new_user_session_url
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def flash_class(level)
    case level
    when :notice then 'alert alert-info'
    when :success then 'alert alert-success'
    when :error then 'alert alert-danger'
    when :alert then 'alert alert-danger'
    else
      'alert alert-info'
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>eShops Manager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-sm navbar-light es-navbar">
      <a class="navbar-brand" href="#">eShops Manager</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <% if user_signed_in? %>
          <ul class="navbar-nav mr-md-auto">
            <li class="nav-item">
              <%= link_to 'Products', root_path, class: 'nav-link' %>
            </li>
          </ul>
        <% end %>
        <% if user_signed_in? %>
            <%= link_to(t('application.auth.logout'), destroy_user_session_path, method: :delete, class: 'btn btn-outline-danger') %>
        <% else %>
            <%= link_to(t('application.auth.login'), new_user_session_path, class: 'btn btn-outline-success ml-auto') %>
        <% end %>
      </div>
    </nav>

    <div class="container">
      <% flash.each do |key, value| %>
        <div class="<%= flash_class(key) + ' mt-3' %>">
          <%= value %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_pagination.html.erb
<% total_pages = (total/per_page.to_f).ceil %>

<div class="pagination d-inline-block">
  <p><%= "Showing page #{page} of #{total_pages}" %></p>
  <p><%= link_to 'Click here to next page', products_path(page: page + 1) %></p>
</div>

app/views/products/_product.html.erb
<div class="product-row row mb-2">
  <div class="card col-12">
    <div class="row">
      <div class="col-3 es-product-image">
        <%= image_tag(product.images.first.url) %>
      </div>
      <div class="col-8 es-product-content">
        <div class="card-block px-3">
          <h4 class="card-title"><%= product.name %></h4>
          <p class="card-text">
            <%= truncate(strip_tags(product.short_description), length: 180) %>
          </p>
          <%= link_to 'See more', { controller: :products, action: :show, id: product.id } %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<h1 class="mt-3">Store Products</h1>

<div class="product-list">
  <%= render partial: 'product', collection: @products.items %>
</div>

<%= render partial: 'pagination', locals: {
    page: @products.page,
    total: @products.results,
    per_page: @products.results_per_page
} %>

app/views/products/partials/_customer.html.erb
<div class="customer-row row">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title"><%= "Customer ##{customer.customer_number}" %></h5>
      <p class="card-text"><%= customer.internal_note %></p>
    </div>
  </div>
</div>

app/views/products/partials/_customers.html.erb
<h3><%= "Customers of product #{@product.name} (#: #{@product.product_number})" %></h3>
<% if @customers.empty? %>
  <p><strong>No customers bought this product yet.</strong></p>
<% else %>
  <%= render partial: 'products/partials/customer', collection: @customers %>
<% end %>

app/views/products/partials/_order.html.erb
<div class="row">
  <div class="card">
    <div class="card-body"><strong>Order number:</strong> <%= order.order_number %></div>
  </div>
</div>

app/views/products/partials/_orders.html.erb
<h3 class="d-inline-block"><%= "#{@title_prefix} Orders" %></h3>

<% if @orders.empty? %>
  <p><strong>There are no orders for the products.</strong></p>
<% else %>
  <%= render partial: 'products/partials/order', collection: @orders %>
<% end %>

app/views/products/partials/_sale.html.erb
<div class="row">
  <div class="col-2">
    <div class="card">
      <div class="card-body">
        <div class="card-title"><h5 class="h4"><%= 'Currency' %></h5></div>
        <div class="card-text"><%= sale.currency %></div>
      </div>
    </div>
  </div>

  <div class="col-3">
    <div class="card">
      <div class="card-body">
        <div class="card-title"><h5 class="h4"><%= 'Gross Revenue' %></h5></div>
        <div class="card-text"><%= number_to_currency(sale.total_gross_revenue, unit: '') %></div>
      </div>
    </div>
  </div>

  <div class="col-3">
    <div class="card">
      <div class="card-body">
        <div class="card-title"><h5 class="h4"><%= 'Net Revenue' %></h5></div>
        <div class="card-text"><%= number_to_currency(sale.total_net_revenue, unit: '') %></div>
      </div>
    </div>
  </div>

  <div class="col-2">
    <div class="card">
      <div class="card-body">
        <div class="card-title"><h5 class="h4"><%= 'Units sold' %></h5></div>
        <div class="card-text"><%= sale.units_sold %></div>
      </div>
    </div>
  </div>

  <div class="col-2">
    <div class="card">
      <div class="card-body">
        <div class="card-title"><h5 class="h4"><%= '# Order' %></h5></div>
        <div class="card-text"><%= sale.total_orders %></div>
      </div>
    </div>
  </div>
</div>

app/views/products/partials/_sales.html.erb
<h2 class="h3">Sale Summary</h2>
<div class="sales-summary container-fluid pb-3">
  <%= render partial: 'products/partials/sale', collection: @sales.sales_per_currency, as: :sale %>
</div>

app/views/products/show.html.erb
<div class="row mb-3">
  <div class="mr-auto es-back-link">
    <%= link_to '<< All Products (go back)', products_path %>
  </div>
</div>

<div class="row es-product-show">
  <div class="col-4 es-product-show__image">
    <%= image_tag(@product.images[0].url, class: 'img-fluid img-thumbnail') %>
  </div>
  <div class="col-8 es-product-show__details">
    <h1 class="h2 mt-1"><%= @product.name %></h1>
    <p><h4 class="font-weight-bold"><%= @product.price_info.price.formatted %></h4></p>
    <hr class="es-product-show__sep">
    <p class="es-product-show__description">
      <%= raw(@product.short_description) %>
    </p>
  </div>
</div>

<% options = [
    ['', ''],
    ['Sale Volume', 'sales'],
    ['Buyers', 'customers'],
    ['Placed Orders', 'orders'],
    ['Not Placed Orders', 'orders_unplaced']
] %>
<h2 class="mt-3">Analytics</h2>
<div class="row es-product-analytics mt-3">
  <%= form_tag('/#') do %>
    <div class="form-group">
      <%= label_tag(:attribute, 'Analytics Attribute') %>
      <%= select_tag(:attribute,
                     options_for_select(options),
                     id: 'product-analytic-select',
                     class: 'form-control',
                     'data-id': @product.id) %>
    </div>
  <% end %>
</div>

<div class="analytics-value">
</div>